[package]
name = "bepeefe"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
object = "0.37.3"
rand = "0.9.2"
thiserror = "2.0.17"

[dev-dependencies]
libc = "0.2"

[profile.release]
debug = true
